# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ghcrctl

before:
  hooks:
    - go mod tidy

builds:
  - id: ghcrctl
    main: .
    binary: ghcrctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mkoepf/ghcrctl/cmd.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mkoepf
    name: ghcrctl
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
